name: deploy gh pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        pnpm-version: [8.3.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: use pnpm.js ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Install dependencies and test
        run: pnpm i

      - name: get current version
        id: get-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "::set-output name=version::$VERSION"

      - name: build App
        run: |
          echo "export const envs = { VITE_BASE_URL: '/tasks', VITE_ENVIRONMENT: 'production', 'VERSION': '${{ steps.get-version.outputs.version }}' };" > src/core/env.ts
          pnpm run build

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/gabrielogregorio/tasks.git

          echo "copy index to 404 page"
          cp build/index.html build/404.html

          npx gh-pages -d build --add -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
